# Generated by Django 5.2.3 on 2025-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
