# Generated by Django 5.2.3 on 2025-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0004_alter_customuser_name_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_id', models.CharField(editable=False, max_length=200, unique=True)),
                ('job_title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('work_mode', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
            ],
        ),
    ]
