# Generated by Django 5.2.3 on 2025-06-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0005_postedjob'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postedjob',
            table='Posted_jobs',
        ),
    ]
