# Generated by Django 5.2.3 on 2025-07-01 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0006_alter_postedjob_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_post_By_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('work_mode', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Save_post_by_user',
            },
        ),
    ]
