# Generated by Django 5.2.3 on 2025-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0007_save_post_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_post_by_user',
            name='company_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
