# Generated by Django 5.2.3 on 2025-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0008_save_post_by_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_post_by_user',
            name='job_id',
            field=models.CharField(max_length=200),
        ),
    ]
